/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package grafica;

import java.io.InputStream;

import javax.swing.BorderFactory;

import java.awt.Color;
import java.awt.Font;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

import componentiaggiuntivi.Musica;

import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.Clip;
import javax.sound.sampled.UnsupportedAudioFileException;
import javax.sound.sampled.LineUnavailableException;


/**
 *
 * @author francescomiccoli
 * @author marzullidino
 * @author sivoroberto
 */
public class InterfacciaIniziale extends javax.swing.JFrame {
    private final Musica musica = new Musica();

    /**
     * Creates new form InterfacciaIniziale
     */
    public InterfacciaIniziale() {
        initComponents();
        setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
    }

    private Font caricaFontUncial(float size) {
        try (InputStream is = getClass().getResourceAsStream("/resource/fonts/UncialAntiqua-Regular.otf")) {
            Font font = Font.createFont(Font.TRUETYPE_FONT, is);
            return font.deriveFont(size);
        } catch (Exception e) {
            e.printStackTrace();
            return new Font("Serif", Font.PLAIN, (int) size); // fallback
        }
    }

    private void aggiungiIcona(javax.swing.JButton bottone, String pathIcona) {
        java.net.URL imgUrl = getClass().getResource(pathIcona);
        if (imgUrl != null) {
            ImageIcon icon = new ImageIcon(imgUrl);
            Image scaled = icon.getImage().getScaledInstance(30, 30, Image.SCALE_SMOOTH);
            bottone.setIcon(new ImageIcon(scaled));
            bottone.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
            bottone.setIconTextGap(10); // Spazio tra icona e testo
        } else {
            System.err.println("Icona non trovata: " + pathIcona);
        }
    }

    /*private void riproduciAudio(String pathAudio) {
        try {
            java.net.URL audioUrl = getClass().getResource(pathAudio);
            if (audioUrl == null) {
                System.err.println("Audio non trovato: " + pathAudio);
                return;
            }

            AudioInputStream audioStream = AudioSystem.getAudioInputStream(audioUrl);
            Clip clip = AudioSystem.getClip();
            clip.open(audioStream);
            clip.start(); // se vuoi loop continuo: clip.loop(Clip.LOOP_CONTINUOUSLY);
        } catch (UnsupportedAudioFileException | java.io.IOException | LineUnavailableException e) {
            e.printStackTrace();
        }
    }*/

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        
        setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
        musica.playMusic("/resource/audio/musica_intro.wav");
        addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowOpened(java.awt.event.WindowEvent evt) {
                if (!musica.isPlaying())
                    musica.playMusic("/resource/audio/musica_intro.wav");
            }
        });

        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            @Override
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                if (!musica.isPlaying())
                    musica.playMusic("/resource/audio/musica_intro.wav");
            }

            @Override
            public void windowLostFocus(java.awt.event.WindowEvent evt) {

            }
        });

        //riproduciAudio("/resource/audio/musica_intro.wav"); 
        
        jPanel1 = new javax.swing.JPanel() {
            private java.awt.Image backgroundImage = null;
            {
                java.net.URL imgUrl = getClass().getResource("/resource/img/schermata_principale.png");
                if (imgUrl != null) {
                    backgroundImage = new javax.swing.ImageIcon(imgUrl).getImage();
                }
            }
            @Override
            protected void paintComponent(java.awt.Graphics g) {
                super.paintComponent(g);
                if (backgroundImage != null) {
                    g.drawImage(backgroundImage, 0, 0, getWidth(), getHeight(), this);
                }
            }
        };

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(true);

        jPanel1.setLayout(null);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1920, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1080, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

    

        jPanel1.setOpaque(false);
        jPanel1.setLayout(new java.awt.GridBagLayout()); // Layout per centrare i componenti

        // Crea un pannello orizzontale per i pulsanti
        javax.swing.JPanel buttonPanel = new javax.swing.JPanel(new java.awt.GridLayout(3, 2, 30, 30));
        buttonPanel.setOpaque(false); // Sfondo trasparente

        
        java.awt.Color textColor = java.awt.Color.BLACK;


        javax.swing.JButton gioca = new javax.swing.JButton("Gioca");
        buttonPanel.add(gioca);
        gioca.setFont(caricaFontUncial(30f));
        gioca.setForeground(textColor);
        aggiungiIcona(gioca, "/resource/img/icone/icona_gioca.png");

        //gioca.setFont(caricaFontUncial(30f));
        //gioca.setFocusPainted(false);
        gioca.setBackground(new Color(100, 150, 150, 155)); // Sfondo semi-trasparente
        //gioca.setForeground(new Color(212, 175, 55));
        //gioca.setBorder(BorderFactory.createLineBorder(new Color(0, 0, 0), 0, true));
        //gioca.setCursor(new Cursor(Cursor.HAND_CURSOR));

        gioca.addActionListener(e -> {
            InterfacciaGioco gioco = null;
            try {
                gioco = new InterfacciaGioco(InterfacciaIniziale.this);
            } catch (Exception e1) {
                // TODO Auto-generated catch block
                e1.printStackTrace();
            }
            gioco.setVisible(true);
            setVisible(false);
        });

       

        javax.swing.JButton carica_partita = new javax.swing.JButton("Carica Partita");
        buttonPanel.add(carica_partita);
        carica_partita.setFont(caricaFontUncial(30f));
        carica_partita.setForeground(textColor);
        carica_partita.setBackground(new Color(100, 150, 150, 155));
        aggiungiIcona(carica_partita, "/resource/img/icone/icona_carica_partita.png");

        JFileChooser fileChooser = new javax.swing.JFileChooser();

        fileChooser.setDialogTitle("Caricamento Salvataggio");
        fileChooser.setCurrentDirectory(new java.io.File("."));
        fileChooser.setFileFilter(new javax.swing.filechooser.FileNameExtensionFilter("Files .dat", "dat"));
        fileChooser.setAcceptAllFileFilterUsed(false);

        carica_partita.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                int valore = fileChooser.showOpenDialog(InterfacciaIniziale.this);
                if (valore == javax.swing.JFileChooser.APPROVE_OPTION) {
                    try {
                        java.io.File file = fileChooser.getSelectedFile();
                        InterfacciaGioco gioco = new InterfacciaGioco(InterfacciaIniziale.this, file);
                        gioco.setVisible(true);
                        setVisible(false);
                    } catch (Exception e) {
                        //musica.playMusic("resource/other/menu_soundtrack.wav");
                        JOptionPane.showMessageDialog(InterfacciaIniziale.this, e.getMessage(), "Errore",
                                JOptionPane.ERROR_MESSAGE);
                    }
                }
            }
        });
  
        javax.swing.JButton classifica = new javax.swing.JButton("Classifica");
        buttonPanel.add(classifica);
        classifica.setFont(caricaFontUncial(30f));
        classifica.setForeground(textColor);
        classifica.setBackground(new Color(100, 150, 150, 155));
        aggiungiIcona(classifica, "/resource/img/icone/icona_classifica.png");
        classifica.addActionListener (e-> {
            //new Classifica();
        });

        javax.swing.JButton impostazioni = new javax.swing.JButton("Impostazioni");
        buttonPanel.add(impostazioni);
        impostazioni.setFont(caricaFontUncial(30f));
        impostazioni.setForeground(textColor);
        impostazioni.setBackground(new Color(100, 150, 150, 155));
        impostazioni.addActionListener(e -> new InterfacciaImpostazioni(this).setVisible(true));
        aggiungiIcona(impostazioni, "/resource/img/icone/icona_opzioni.png");

        javax.swing.JButton esci = new javax.swing.JButton("Esci");
        buttonPanel.add(esci);
        esci.setFont(caricaFontUncial(30f));
        esci.setForeground(textColor);
        esci.setBackground(new Color(100, 150, 150, 155));
        aggiungiIcona(esci, "/resource/img/icone/icona_esci.png");
        
        esci.addActionListener(e -> {
            int scelta = JOptionPane.showConfirmDialog(
                    null,
                    "Sei sicuro di voler uscire?",
                    "Conferma Uscita",
                    JOptionPane.YES_NO_OPTION,
                    JOptionPane.WARNING_MESSAGE
            );
            if (scelta == JOptionPane.YES_OPTION) {
                System.exit(0); // chiude il programma
            }
        });

        javax.swing.JButton riconoscimenti = new javax.swing.JButton("Riconoscimenti");
        buttonPanel.add(riconoscimenti);
        riconoscimenti.setFont(caricaFontUncial(30f));
        riconoscimenti.setForeground(textColor);
        riconoscimenti.setBackground(new Color(100, 150, 150, 155));
        aggiungiIcona(riconoscimenti, "/resource/img/icone/icona_riconoscimenti.png");

            
        

        // Centra il pannello dei pulsanti usando GridBagConstraints
        java.awt.GridBagConstraints gbc = new java.awt.GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.anchor = java.awt.GridBagConstraints.CENTER;
        jPanel1.add(buttonPanel, gbc);

        // ...continua con il resto del tuo codice per layout e pack...
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(true);

        getContentPane().setLayout(new java.awt.BorderLayout());
        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfacciaIniziale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfacciaIniziale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfacciaIniziale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfacciaIniziale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfacciaIniziale().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton gioca;
    private javax.swing.JButton carica_partita;
    private javax.swing.JButton impostazioni;
    private javax.swing.JButton esci;
    private javax.swing.JButton riconoscimenti;
    
    // End of variables declaration//GEN-END:variables
}
